MVC/Controllers/CodingLanguagesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Data;

namespace MVC.Controllers
{
    public class CodingLanguagesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: CodingLanguages
        public ActionResult Index()
        {
            return View(db.CodingLanguages.ToList());
        }

        // GET: CodingLanguages/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CodingLanguage codingLanguage = db.CodingLanguages.Find(id);
            if (codingLanguage == null)
            {
                return HttpNotFound();
            }
            return View(codingLanguage);
        }

        // GET: CodingLanguages/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CodingLanguages/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CodingLanguageId,CodingLanguageName")] CodingLanguage codingLanguage)
        {
            if (ModelState.IsValid)
            {
                db.CodingLanguages.Add(codingLanguage);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(codingLanguage);
        }

        // GET: CodingLanguages/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CodingLanguage codingLanguage = db.CodingLanguages.Find(id);
            if (codingLanguage == null)
            {
                return HttpNotFound();
            }
            return View(codingLanguage);
        }

        // POST: CodingLanguages/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CodingLanguageId,CodingLanguageName")] CodingLanguage codingLanguage)
        {
            if (ModelState.IsValid)
            {
                db.Entry(codingLanguage).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(codingLanguage);
        }

        // GET: CodingLanguages/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CodingLanguage codingLanguage = db.CodingLanguages.Find(id);
            if (codingLanguage == null)
            {
                return HttpNotFound();
            }
            return View(codingLanguage);
        }

        // POST: CodingLanguages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CodingLanguage codingLanguage = db.CodingLanguages.Find(id);
            db.CodingLanguages.Remove(codingLanguage);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVC/Controllers/JobPostsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Data;
using Microsoft.AspNet.Identity;
using Models.JobPost;
using Services;

namespace MVC.Controllers
{
    public class JobPostsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private JobPostService _jobPostService;
        private string _userId;

        // GET: JobPosts
        public ActionResult Index()
        {
            var jobPosts = db.JobPosts.Where(e => e.IsActive == true).Include(j => j.Employer).Include(j => j.Freelancer);
            return View(jobPosts.ToList());
        }

        // GET: JobPosts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            JobPost jobPost = db.JobPosts.Find(id);
            if (jobPost == null)
            {
                return HttpNotFound();
            }
            return View(jobPost);
        }

        // GET: JobPosts/Create
        public ActionResult Create()
        {
            ViewBag.EmployerId = new SelectList(db.Employers, "EmployerId", "FirstName");
            ViewBag.StateId = new SelectList(db.States, "StateId", "StateName");
            return View();
        }

        // POST: JobPosts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(JobPostCreate jobPost)
        {
            if (ModelState.IsValid)
            {
                _userId = User.Identity.GetUserId();
                _jobPostService = new JobPostService(_userId);
                _jobPostService.CreateJobPost(jobPost);
                return RedirectToAction("Index");
            }

            return View(jobPost);
        }

        // GET: JobPosts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            JobPost jobPost = db.JobPosts.Find(id);
            if (jobPost == null)
            {
                return HttpNotFound();
            }
            ViewBag.EmployerId = new SelectList(db.Employers, "EmployerId", "FirstName", jobPost.EmployerId);
            ViewBag.FreelancerId = new SelectList(db.Freelancers, "FreelancerId", "FirstName", jobPost.FreelancerId);
            ViewBag.StateId = new SelectList(db.States, "StateId", "StateName");
            return View(jobPost);
        }

        // POST: JobPosts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "JobPostId,JobTitle,Content,StateName,IsAwarded,CreatedDate,ModifiedDate,IsActive,EmployerId,FreelancerId")] JobPost jobPost)
        {
            if (ModelState.IsValid)
            {
                db.Entry(jobPost).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EmployerId = new SelectList(db.Employers, "EmployerId", "FirstName", jobPost.EmployerId);
            ViewBag.FreelancerId = new SelectList(db.Freelancers, "FreelancerId", "FirstName", jobPost.FreelancerId);
            ViewBag.StateId = new SelectList(db.States, "StateId", "StateName");
            return View(jobPost);
        }

        // GET: JobPosts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            JobPost jobPost = db.JobPosts.Find(id);
            if (jobPost == null)
            {
                return HttpNotFound();
            }
            return View(jobPost);
        }

        // POST: JobPosts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            JobPost jobPost = db.JobPosts.Find(id);
            db.JobPosts.Remove(jobPost);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Styles/stylesheet.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans&family=Raleway:wght@800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lexend+Tera&display=swap" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-primary">
        <a class="navbar-brand" href="#"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="nav nav-pills mx-auto">
                <li class="nav-item">
                    @Html.ActionLink("DevWork", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("About", "About", "Home", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Contact", "Contact", "Home", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Get Started
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        @Html.ActionLink("Employers", "Index", "Employers", null, new { @class = "dropdown-item" })
                        @Html.ActionLink("Freelancers", "Index", "Freelancers", null, new { @class = "dropdown-item" })
                        @Html.ActionLink("Job Posts", "Index", "JobPosts", null, new { @class = "dropdown-item" })
                        @Html.ActionLink("Messages", "Index", "Messages", null, new { @class = "dropdown-item" })
                        @Html.ActionLink("Coding Languages", "Index", "CodingLanguages", null, new { @class = "dropdown-item" })
                    </div>
                </li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - DevWork</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>